### ISSUE TITLE
Kanban board setup

### ISSUE THREAD

**Issue by gandradep** [gandradep/rocketMission#45]
[github project](https://github.com/gandradep/rocketMission/projects/2)
This is team comprises of 2 members.

**Comment by Reem-lab** [comment]
# Hi  Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media3.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights
- Great job working on the kanban set up 😊🔥🚀♻

## Required Changes ♻️
_Check the comments under the review._
- [ ] Great job creating the cards and assign it but I think you assign to one of the team 10 tasks and the other 7 tasks I think it would be great if you divide them fairly and the set up you can make it toghether as pair programming ♻🚀🔥😊📌

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by gandradep** [comment]
@Reem-lab thanks for the suggestion.

**Comment by brytebee** [comment]
Hi, @ 👋,

##

### Highlights💡
- Good commit message.✔️ 
- Good PR Summary.✔️
- Great UI design.✔️
- App functions as it should.✔️

##

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)

##

###  **Optional Suggestions:**
- Kindly point the link you've supplied to [your kanban board](https://github.com/gandradep/rocketMission/projects/2)

##

Good luck! 🎉 

------

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by gandradep** [comment]
@brytebee thank you for the review. I updated the link as you suggested.
